### ISSUE TITLE
Unable To Manually Updated Episode Watched State

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/ShokoClient#453] opened 2016-09-05 18:07 UTC
When clicking the unwatched icon, I get the following error message. 

![unknown](https://cloud.githubusercontent.com/assets/9443295/18254985/d70c77e6-7358-11e6-8f90-9ef5708249bf.png)

Using a fresh SQLite DB.

**Comment by da3dsoul** [comment] 2016-09-23 16:20
Fixed, but I am experiencing it wiped on JMMServer restart.

**Comment by ElementalCrisis** [comment] 2016-09-24 10:51
Just checked, Watched state is saved and correct after restarting JMM Server. Can you double-check with latest master?

**Comment by da3dsoul** [comment] 2016-09-24 10:52
Always on latest master. I think it's some kind of SQL error. I'll see if I can find some info in logs

**Comment by da3dsoul** [comment] 2016-09-25 06:07
I'm seeing absolutely no trace as to why this happens. I've been busy with the Nancy stuff...and anti-normalfag protests (life).

**Comment by ElementalCrisis** [comment] 2016-12-08 02:30
Any update @da3dsoul?

**Comment by da3dsoul** [comment] 2016-12-08 06:38
I'll close this. I've tracked down the cause for the watched states being wiped

**Closed by da3dsoul** 2016-12-08 06:38 UTC
Labels: Bug - Low Priority
